#!/usr/bin/env bash

# Simple script to ease the `dwm' patching process

# Copyright 03/01/2015 Aaron Caffrey https://github.com/wifiextender

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.


patches_arr=(
    'my_patch.diff' 'dwm-cdec978-center.diff'
    'save_float.diff' 'statuscolours.diff'
    'underline.diff' 'push.diff' 'uselessgap3.diff'
    'remove_monocle.diff'
)


for x in ${patches_arr[@]}; do
    patch -p1 < "patches/$x";
done
